### ISSUE TITLE
Test fails with AssertionFailed 42 != 0 on mvn v3.5.0, jdk v1.8.0

### ISSUE THREAD

**Issue by chrisinmtown** [mp911de/rest-api-test#4]
Cloned fresh, compiled cleanly, so I ran "mvn test" using maven v3.5.0 and JDK 1.8.0_91. But 2 of 3 tests fail, an abbreviated log is below.  

```
Running biz.paluch.rest.test.InMemoryRestTest
KEEPALIVE!: true
[Tue Nov 14 13:15:21 EST 2017] Servlet for path '/' already defined and no default will be used.
[Tue Nov 14 13:15:21 EST 2017] TJWS httpd localhost - SimpleAcceptor ServerSocket[addr=localhost/127.0.0.1,localport=49900] is listening.
[Tue Nov 14 13:15:22 EST 2017] Accept: java.net.SocketException: Socket closed
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.67 sec <<< FAILURE!
postSimpleBody(biz.paluch.rest.test.InMemoryRestTest)  Time elapsed: 0.238 sec  <<< FAILURE!
java.lang.AssertionError: expected:<42> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at biz.paluch.rest.test.InMemoryRestTest.postSimpleBody(InMemoryRestTest.java:56)
```
Finally here's the result:
```
Failed tests:   postSimpleBody(biz.paluch.rest.test.InMemoryRestTest): expected:<42> but was:<0>
  postWithMocking(biz.paluch.rest.test.InMemoryRestWithMockitoTest): expected:<42> but was:<0>
```
Please advise, thanks for listening.

**Comment by chrisinmtown** [comment]
Please see my pull request for the fix.

**Comment by mp911de** [comment]
That's fixed now.
